// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ooygvrkydysefvhimbko.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9veWd2cmt5ZHlzZWZ2aGltYmtvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQwMTk5MzQsImV4cCI6MjA1OTU5NTkzNH0.zAAgVEdcS3eBFLzjZa598xdxxLb3c8_Z2LgoG19KYgE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);